[package]
name = "wicket-core"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.10.0"
encoding_rs = "0.8.35"
thiserror.workspace = true
wicket-util = { path = "../wicket-util/"}
wicket-request = { path = "../wicket-request/"}
